IMAGE_QUERIES = [
    "image with text", "webpage with text", "bookpage with text", 
    "magazine with text", "newspaper with text", "handwritten note", 
    "street sign", "billboard", "menu board", "product label", 
    "business card", "movie subtitle", "presentation slide", 
    "infographic", "poster with text", "comic book page", 
    "textbook page", "receipt", "document scan", "whiteboard writing",
    "graffiti", "storefront sign", "license plate", "captcha image", 
    "meme with text", "social media post", "text message screenshot", 
    "email screenshot", "forum post", "book cover", "album cover", 
    "movie poster", "road sign", "restaurant menu", "concert ticket",
    "bus schedule", "train timetable", "flight information board",
    "classroom blackboard", "sticky note", "to-do list", 
    "calendar page", "wedding invitation", "business flyer", 
    "resume document", "legal document", "medical prescription", 
    "nutrition label", "warning sign", "instruction manual page", 
    "map with labels", "sheet music", "crossword puzzle", 
    "sudoku puzzle", "word search puzzle", "captioned image", 
    "news ticker", "closed caption", "subtitled video frame", 
    "comic strip", "product packaging", "store display", 
    "TV news ticker", "tourist attraction sign", "museum exhibit label",
    "book spine", "instructional poster", "airline boarding pass", 
    "airport signage", "public transport map", "name tag", 
    "conference badge", "clothing tag", "shoe label", "price tag", 
    "vehicle registration sticker", "warranty card", "greeting card", 
    "recipe card", "notebook page", "research paper page", "magazine ad", 
    "digital billboard", "game screen with HUD text", "sports scoreboard",
    "phone app notification", "streaming interface with captions", 
    "fitness tracker screen", "ATM screen", "control panel label", 
    "science journal page", "weather forecast screen", "school report card",
    "gym class schedule", "voting ballot", "event ticket", 
    "digital map with place names", "lottery ticket", "horoscope page", 
    "hotel room service menu", "exam paper", "beverage can label", 
    "toy packaging", "pharmacy label", "FAQ page screenshot", 
    "software license agreement", "e-book page", "menu screen in video game", 
    "GPS navigation screen", "emergency exit sign", "restaurant table tent", 
    "conference schedule", "ID card", "police report", "credit card", 
    "membership card", "work badge", "school ID", "COVID vaccination card", 
    "utility bill", "advertisement on social media", "promotional flyer", 
    "health insurance card", "bank statement", "airplane safety card", 
    "children's storybook page", "restaurant loyalty card", "pharmacy bag label",
    "university acceptance letter", "loan document", "court order", 
    "medical diagnostic report", "insurance policy document", "company invoice", 
    "employee contract", "product warranty document", "nutrition facts panel",
    "department store sign", "election ballot", "time schedule", 
    "real estate listing", "digital shopping cart", "delivery confirmation slip",
    "personal diary page", "exam results slip", "lab report", "service receipt",
    "project status report", "meeting agenda", "wedding announcement",
    "baby announcement", "customs declaration form", "school announcement board"
]
RAW_IMAGE_DIR = "../text-sharpener/data/raw"
PROCESSED_IMAGE_DIR = "../text-sharpener/data/processed"
BLURRED_IMAGE_DIR = "../text-sharpener/data/blurred"
NUM_PER_QUERY = 60
IMAGE_SIZE = 512